---
- name: Configure and Start server.js as a Service
  hosts: localhost
  become: yes # Führt Aufgaben als root aus
  tasks:
  - name: Stelle sicher, dass Node.js installiert ist
    command: node --version
    ignore_errors: yes
    register: node_installed
    changed_when: false

  - name: Installiere Node.js
    apt:
      name: nodejs
      state: present
    when: node_installed.failed

  - name: Überprüfe ob npm installiert ist
    command: npm --version
    ignore_errors: yes
    register: npm_installed
    changed_when: false

  - name: Installiere npm
    apt:
      name: npm
      state: present
    when: npm_installed.failed

  - name: Installiere erforderliche npm-Pakete
    command: npm install mongoose cors express
    args:
      chdir: /root/TODO-main/Todo/todo-backend/
    become: yes
    become_user: root

  - name: Erstelle eine Systemd-Service-Datei für server.js
    copy:
      content: |
        [Unit]
        Description=server.js - Enable TODO-App
        After=network.target

        [Service]
        Environment=NODE_PORT=3000
        Type=simple
        User=root
        ExecStart=/usr/bin/node /root/TODO-main/Todo/todo-backend/server.js
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/todo-app.service
    notify: Starte todo-app Service

  handlers:
    - name: Starte todo-app Service
      systemd:
        name: todo-app
        state: started
        enabled: yes
        daemon_reload: yes

