---
- name: Install Docker
  hosts: localhost
  become: yes  # Verwenden Sie sudo
  tasks:
    - name: Update APT 
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: docker.io
        state: latest
      tags: setup

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest
      tags: setup

    - name: Start Docker Containers
      docker_compose:
        project_src: /root/Todo/mongo/
        state: present
        restarted: yes
      tags: docker
        
    - name: Run Docker Compose up
      ansible.builtin.shell: cd /root/Todo-main/Todo/mongo && docker-compose up -d
      args:
        executable: /bin/bash
