---
- name: Install Node.js and npm
  hosts: all 
  become: yes  
  tasks:
    - name: Install Node.js and npm from NodeSource
      ansible.builtin.block:
        - name: Download Node.js setup script
          ansible.builtin.get_url:
            url: https://deb.nodesource.com/setup_16.x
            dest: /tmp/node_setup.sh
            mode: '0755'

        - name: Execute the Node.js setup script
          ansible.builtin.shell: /tmp/node_setup.sh
          args:
            removes: /tmp/node_setup.sh

        - name: Install Node.js and npm
          ansible.builtin.apt:
            name: nodejs
            state: latest
            update_cache: yes
